import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {supabase} from "./lib/supabase";
import {LayoutDashboard,Film,Layers, Bell, LogOut, Plus, Trash2, Edit, Play, Search, Upload} from "lucide-react";
import "./styles.css";
type Movie={id:string;title:string;synopsis?:string;poster_url?:string;backdrop_url?:string;stream_url?:string;duration_minutes?:number;rating?:number;release_year?:number;category_id?:string;category_name?:string;type:"movie"|"series";total_seasons?:number;views_count?:number;is_featured?:boolean;is_trending?:boolean;is_free?:boolean;badge_label?:string;};
const empty:Movie={id:"",title:"",synopsis:"",poster_url:"",backdrop_url:"",stream_url:"",duration_minutes:0,rating:0,release_year:new Date().getFullYear(),category_id:"",category_name:"",type:"movie",total_seasons:1,views_count:0,is_featured:false,is_trending:false,is_free:true,badge_label:""};
function App(){const [pin,setPin]=useState("");const [authed,setAuthed]=useState(false);const [tab,setTab]=useState("dashboard");const [movies,setMovies]=useState<Movie[]>([]);const [categories,setCategories]=useState<any[]>([]);const [tokens,setTokens]=useState(0);const [episodes,setEpisodes]=useState(0);const [editing,setEditing]=useState<Movie|null>(null);const [q,setQ]=useState("");const [toast,setToast]=useState("");
const load=async()=>{const [m,c,t,e]=await Promise.all([supabase.from("movies").select("*").order("created_at",{ascending:false}),supabase.from("categories").select("*").order("name"),supabase.from("push_tokens").select("token",{count:"exact",head:true}),supabase.from("episodes").select("id",{count:"exact",head:true})]);setMovies(m.data||[]);setCategories(c.data||[]);setTokens(t.count||0);setEpisodes(e.count||0)};
useEffect(()=>{if(authed)load()},[authed]);
const filtered=useMemo(()=>movies.filter(m=>(m.title+" "+(m.category_name||"")).toLowerCase().includes(q.toLowerCase())),[movies,q]);
async function save(){if(!editing?.title)return;const payload={...editing,updated_at:Date.now()};const {error}=await supabase.from("movies").upsert(payload);setToast(error?error.message:"Contenido guardado");setEditing(null);load()}
async function remove(id:string){if(!confirm("¿Eliminar este contenido?"))return;const {error}=await supabase.from("movies").delete().eq("id",id);setToast(error?error.message:"Contenido eliminado");load()}
if(!authed)return <div className="login"><div className="login-card"><div className="logo">STREAM<span>BOX</span></div><h1>Panel de administración</h1><p>Acceso privado</p><input type="password" placeholder="PIN de administrador" value={pin} onChange={e=>setPin(e.target.value)}/><button onClick={()=>pin===import.meta.env.VITE_ADMIN_PIN?setAuthed(true):setToast("PIN incorrecto")}>Entrar</button>{toast&&<small>{toast}</small>}</div></div>;
return <div className="app"><aside><div className="logo">STREAM<span>BOX</span></div>{[["dashboard","Dashboard",LayoutDashboard],["catalog","Catálogo",Film],["episodes","Episodios",Layers],["notifications","Notificaciones",Bell]].map(([id,label,Icon]:any)=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}<button className="nav logout" onClick={()=>setAuthed(false)}><LogOut size={18}/>Salir</button></aside><main><header><div><p className="eyebrow">ADMIN CONSOLE</p><h1>{tab==="dashboard"?"Resumen":tab==="catalog"?"Catálogo":tab==="episodes"?"Episodios":"Notificaciones"}</h1></div><div className="status">● Sistema conectado</div></header>{tab==="dashboard"&&<section className="grid metrics"><Metric label="Películas y series" value={movies.length}/><Metric label="Episodios" value={episodes}/><Metric label="Dispositivos FCM" value={tokens}/><Metric label="Destacadas" value={movies.filter(m=>m.is_featured).length}/></section>}{tab==="catalog"&&<><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Buscar título o categoría..." value={q} onChange={e=>setQ(e.target.value)}/></div><button onClick={()=>setEditing({...empty,id:crypto.randomUUID()})}><Plus size={18}/>Agregar</button></div><div className="catalog">{filtered.map(m=><article className="movie"><img src={m.poster_url||"https://placehold.co/180x270/16161f/ffffff?text=STREAMBOX"}/><div className="movie-info"><div className="pill">{m.type}</div><h3>{m.title}</h3><p>{m.category_name||"Sin categoría"} · {m.release_year||"—"}</p><p className="muted">{m.synopsis||"Sin sinopsis"}</p><div className="actions"><button className="icon" onClick={()=>setEditing(m)}><Edit size={16}/></button><button className="icon" onClick={()=>remove(m.id)}><Trash2 size={16}/></button>{m.stream_url&&<a className="icon" href={m.stream_url} target="_blank"><Play size={16}/></a>}</div></div></article>)}</div></>}{tab==="episodes"&&<Empty text="Seleccioná una serie desde tu módulo de episodios. Podés extender esta vista para CRUD de episodes."/>}{tab==="notifications"&&<Notification movies={movies} tokens={tokens} setToast={setToast}/>} {editing&&<Editor item={editing} categories={categories} setItem={setEditing} save={save} close={()=>setEditing(null)}/>} {toast&&<div className="toast" onClick={()=>setToast("")}>{toast}</div>}</main></div>}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><p>{label}</p><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Editor({item,categories,setItem,save,close}:any){const set=(k:string,v:any)=>setItem({...item,[k]:v});return <div className="overlay"><div className="modal"><div className="modal-head"><h2>{item.title?"Editar contenido":"Nuevo contenido"}</h2><button onClick={close}>×</button></div><div className="form-grid">{["title","synopsis","poster_url","backdrop_url","stream_url","badge_label"].map(k=><label className={k==="synopsis"?"wide":""}>{k}<input value={item[k]||""} onChange={e=>set(k,e.target.value)}/></label>)}<label>Año<input type="number" value={item.release_year||""} onChange={e=>set("release_year",+e.target.value)}/></label><label>Duración<input type="number" value={item.duration_minutes||0} onChange={e=>set("duration_minutes",+e.target.value)}/></label><label>Rating<input type="number" min="0" max="5" step=".1" value={item.rating||0} onChange={e=>set("rating",+e.target.value)}/></label><label>Tipo<select value={item.type} onChange={e=>set("type",e.target.value)}><option value="movie">Película</option><option value="series">Serie</option></select></label><label>Categoría<select value={item.category_id||""} onChange={e=>{const c=categories.find((x:any)=>x.id===e.target.value);setItem({...item,category_id:e.target.value,category_name:c?.name||""})}}><option value="">Seleccionar</option>{categories.map((c:any)=><option value={c.id}>{c.name}</option>)}</select></label>{["is_featured","is_trending","is_free"].map(k=><label className="check"><input type="checkbox" checked={!!item[k]} onChange={e=>set(k,e.target.checked)}/>{k}</label>)}</div><div className="modal-actions"><button className="secondary" onClick={close}>Cancelar</button><button onClick={save}>Guardar</button></div></div></div>}
function Notification({movies,tokens,setToast}:any){const [title,setTitle]=useState("🔥 ¡Nuevo estreno disponible!");const [body,setBody]=useState("");const [movie,setMovie]=useState("");const send=async()=>{const {data,error}=await supabase.functions.invoke("send-push-notification",{body:{title,body,movie_id:movie||null,target:"all"}});if(error){setToast(error.message);return}await supabase.from("push_notifications").insert({title,body,movie_id:movie||null,target:"all",status:"sent",created_at:Date.now()});setToast(data?.message||"Notificación enviada")};return <div className="notification"><div className="panel"><h2>Enviar a todos</h2><p className="muted">{tokens} dispositivos registrados</p><label>Título<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Mensaje<textarea value={body} onChange={e=>setBody(e.target.value)}/></label><label>Deep link<select value={movie} onChange={e=>setMovie(e.target.value)}><option value="">Sin vincular</option>{movies.map((m:any)=><option value={m.id}>{m.title}</option>)}</select></label><button onClick={send}>Enviar notificación</button></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);